version: '3'
services:
  python:
    command: flask run --host=0.0.0.0 --debug
    build:
      context: .
    ports:
     - 8080:5000
    env_file:
     - ./app/.env
    volumes:
     - ./app:/app
     - ./db:/db
